export const opportunities = [
  {
    id: 1,
    oppurtunity_id: 'ABD/GB/2024-2025/91',
    company: 'ARBL',
    department: 'ABD-Assembly',
    plant: 'ABD',
    pl_id: 122394,
    category: 'Green Belt',
    project_type: 'Type-1',
    savings_type: 'Medium',
    estimated_savings: '>1 and <=5 Lakh',
    pl_name: 'Arun',
    bussiness_unit: 'Lead Acid',
    problem_impact: 'Medium Impact',
    status: 'Open for Assigning',
    impact_socre: 27,
    problem_statement: 'Reduction of cycle time in the GROWIN COS process',
  },
  {
    id: 2,
    oppurtunity_id: 'MVRLA/BB/2024-2025/91',
    company: 'ARBL',
    department: 'MVRLA- Grid Casting',
    plant: 'MVRLA',
    pl_id: 1022323,
    pl_name: 'Arun',
    category: 'Black Belt',
    project_type: 'Type-2',
    savings_type: 'Low',
    estimated_savings: '>1 and <=5 Lakh',
    bussiness_unit: 'Lead Acid',
    problem_impact: 'High Impact',
    status: 'Open for Assigning',
    impact_socre: 92,
    problem_statement: 'Reduction of MF5 (TVS) LOCV rejections',
  },
  {
    id: 3,
    oppurtunity_id: 'LVRLA/BB/2024-2025/91',
    company: 'ARBL',
    department: 'LVRLA - Oxide Plant',
    plant: 'LVRLA',
    pl_id: 120394,
    category: 'Black Belt',
    project_type: 'Type-3',
    savings_type: 'High',
    pl_name: 'Arun',
    bussiness_unit: 'Lead Acid',
    estimated_savings: '<= 1 Lakh',
    problem_impact: 'Low Impact',
    status: 'Project Assign Pending (CIHead)',
    impact_socre: 12,
    problem_statement: 'Reduction of MF5 (TVS) LOCV rejections',
  },
  {
    id: 4,
    oppurtunity_id: 'SBD2/GB/2024-2025/91',
    company: 'ARBL',
    department: 'SBD - Grid Casting',
    plant: 'SBD',
    pl_id: 1000221,
    category: 'Green Belt',
    pl_name: 'Arun',
    bussiness_unit: 'Lead Acid',
    project_type: 'Type-4',
    savings_type: 'Low',
    estimated_savings: '>1 and <=5 Lakh',
    problem_impact: 'Low Impact',
    status: 'Open for Assigning',
    impact_socre: 25,
    problem_statement: "Reduce Briquette's consumption in Powder coating process",
  },
  {
    id: 5,
    oppurtunity_id: 'SBD2/GB/2024-2025/91',
    company: 'ARBL',
    department: 'LVRLA',
    plant: 'MVRLA',
    pl_id: 10002394,
    bussiness_unit: 'Lead Acid',
    category: 'Green Belt',
    project_type: 'Type-5',
    pl_name: 'Arun',
    savings_type: 'Low',
    estimated_savings: '>1 and <=5 Lakh',
    problem_impact: 'Low Impact',
    impact_socre: 32,
    status: 'Open for Assigning',
    problem_statement: 'Reduction of cycle time in the GROWIN COS process',
  },
  {
    id: 1,
    oppurtunity_id: 'ABD/GB/2024-2025/91',
    company: 'ARBL',
    department: 'ABD-Assembly',
    plant: 'ABD',
    pl_id: 122394,
    category: 'Green Belt',
    project_type: 'Type-1',
    savings_type: 'Medium',
    estimated_savings: '>1 and <=5 Lakh',
    pl_name: 'Arun',
    bussiness_unit: 'Lead Acid',
    problem_impact: 'Medium Impact',
    status: 'Open for Assigning',
    impact_socre: 27,
    problem_statement: 'Reduction of cycle time in the GROWIN COS process',
  },
  {
    id: 2,
    oppurtunity_id: 'MVRLA/BB/2024-2025/91',
    company: 'ARBL',
    department: 'MVRLA- Grid Casting',
    plant: 'MVRLA',
    pl_id: 1022323,
    pl_name: 'Arun',
    category: 'Black Belt',
    project_type: 'Type-2',
    savings_type: 'Low',
    estimated_savings: '>1 and <=5 Lakh',
    bussiness_unit: 'Lead Acid',
    problem_impact: 'High Impact',
    status: 'Open for Assigning',
    impact_socre: 92,
    problem_statement: 'Reduction of MF5 (TVS) LOCV rejections',
  },
  {
    id: 3,
    oppurtunity_id: 'LVRLA/BB/2024-2025/91',
    company: 'ARBL',
    department: 'LVRLA - Oxide Plant',
    plant: 'LVRLA',
    pl_id: 120394,
    category: 'Black Belt',
    project_type: 'Type-3',
    savings_type: 'High',
    pl_name: 'Arun',
    bussiness_unit: 'Lead Acid',
    estimated_savings: '<= 1 Lakh',
    problem_impact: 'Low Impact',
    status: 'Project Assign Pending (CIHead)',
    impact_socre: 12,
    problem_statement: 'Reduction of MF5 (TVS) LOCV rejections',
  },
  {
    id: 4,
    oppurtunity_id: 'SBD2/GB/2024-2025/91',
    company: 'ARBL',
    department: 'SBD - Grid Casting',
    plant: 'SBD',
    pl_id: 1000221,
    category: 'Green Belt',
    pl_name: 'Arun',
    bussiness_unit: 'Lead Acid',
    project_type: 'Type-4',
    savings_type: 'Low',
    estimated_savings: '>1 and <=5 Lakh',
    problem_impact: 'Low Impact',
    status: 'Open for Assigning',
    impact_socre: 25,
    problem_statement: "Reduce Briquette's consumption in Powder coating process",
  },
  {
    id: 5,
    oppurtunity_id: 'SBD2/GB/2024-2025/91',
    company: 'ARBL',
    department: 'LVRLA',
    plant: 'MVRLA',
    pl_id: 10002394,
    bussiness_unit: 'Lead Acid',
    category: 'Green Belt',
    project_type: 'Type-5',
    pl_name: 'Arun',
    savings_type: 'Low',
    estimated_savings: '>1 and <=5 Lakh',
    problem_impact: 'Low Impact',
    impact_socre: 32,
    status: 'Open for Assigning',
    problem_statement: 'Reduction of cycle time in the GROWIN COS process',
  },
  {
    id: 1,
    oppurtunity_id: 'ABD/GB/2024-2025/91',
    company: 'ARBL',
    department: 'ABD-Assembly',
    plant: 'ABD',
    pl_id: 122394,
    category: 'Green Belt',
    project_type: 'Type-1',
    savings_type: 'Medium',
    estimated_savings: '>1 and <=5 Lakh',
    pl_name: 'Arun',
    bussiness_unit: 'Lead Acid',
    problem_impact: 'Medium Impact',
    status: 'Open for Assigning',
    impact_socre: 27,
    problem_statement: 'Reduction of cycle time in the GROWIN COS process',
  },
  {
    id: 2,
    oppurtunity_id: 'MVRLA/BB/2024-2025/91',
    company: 'ARBL',
    department: 'MVRLA- Grid Casting',
    plant: 'MVRLA',
    pl_id: 1022323,
    pl_name: 'Arun',
    category: 'Black Belt',
    project_type: 'Type-2',
    savings_type: 'Low',
    estimated_savings: '>1 and <=5 Lakh',
    bussiness_unit: 'Lead Acid',
    problem_impact: 'High Impact',
    status: 'Open for Assigning',
    impact_socre: 92,
    problem_statement: 'Reduction of MF5 (TVS) LOCV rejections',
  },
  {
    id: 3,
    oppurtunity_id: 'LVRLA/BB/2024-2025/91',
    company: 'ARBL',
    department: 'LVRLA - Oxide Plant',
    plant: 'LVRLA',
    pl_id: 120394,
    category: 'Black Belt',
    project_type: 'Type-3',
    savings_type: 'High',
    pl_name: 'Arun',
    bussiness_unit: 'Lead Acid',
    estimated_savings: '<= 1 Lakh',
    problem_impact: 'Low Impact',
    status: 'Project Assign Pending (CIHead)',
    impact_socre: 12,
    problem_statement: 'Reduction of MF5 (TVS) LOCV rejections',
  },
  {
    id: 4,
    oppurtunity_id: 'SBD2/GB/2024-2025/91',
    company: 'ARBL',
    department: 'SBD - Grid Casting',
    plant: 'SBD',
    pl_id: 1000221,
    category: 'Green Belt',
    pl_name: 'Arun',
    bussiness_unit: 'Lead Acid',
    project_type: 'Type-4',
    savings_type: 'Low',
    estimated_savings: '>1 and <=5 Lakh',
    problem_impact: 'Low Impact',
    status: 'Open for Assigning',
    impact_socre: 25,
    problem_statement: "Reduce Briquette's consumption in Powder coating process",
  },
  {
    id: 5,
    oppurtunity_id: 'SBD2/GB/2024-2025/91',
    company: 'ARBL',
    department: 'LVRLA',
    plant: 'MVRLA',
    pl_id: 10002394,
    bussiness_unit: 'Lead Acid',
    category: 'Green Belt',
    project_type: 'Type-5',
    pl_name: 'Arun',
    savings_type: 'Low',
    estimated_savings: '>1 and <=5 Lakh',
    problem_impact: 'Low Impact',
    impact_socre: 32,
    status: 'Open for Assigning',
    problem_statement: 'Reduction of cycle time in the GROWIN COS process',
  },
];

export const tools = [
  {
    id: 1,
    name: "1 Sample 't' test",
    category: 'Black Belt',
    status: 'Active',
  },
  {
    id: 2,
    name: 'Pareto Charts',
    category: 'Green Belt',
    status: 'Active',
  },
  {
    id: 3,
    name: 'P-chart	',
    category: 'Black Belt',
    status: 'Active',
  },
  {
    id: 4,
    name: 'Histogram',
    category: 'Green Belt',
    status: 'Active',
  },
  {
    id: 5,
    name: 'Brainstorming	',
    category: 'Black Belt',
    status: 'Active',
  },
  {
    id: 6,
    name: 'Startification	',
    category: 'Green Belt',
    status: 'Active',
  },
  {
    id: 1,
    name: 'Process Mapping	',
    category: 'Black Belt',
    status: 'Active',
  },
  {
    id: 2,
    name: 'Gemba Observation	',
    category: 'Green Belt',
    status: 'Active',
  },
  {
    id: 3,
    name: 'ISO plot	',
    category: 'Black Belt',
    status: 'Active',
  },
  {
    id: 4,
    name: 'Attribute Agreement Analysis	',
    category: 'Green Belt',
    status: 'Active',
  },
  {
    id: 5,
    name: 'Multi-Vari Analysis	',
    category: 'Black Belt',
    status: 'Active',
  },
  {
    id: 6,
    name: 'Graphs	',
    category: 'Green Belt',
    status: 'Active',
  },
];

export const requestPlant = [
  {
    id: 1,
    employee_id: '1002345',
    employee_name: 'Arun Kumar',
    current_plant: 'ABD',
    new_plant: 'ABD1',
    status: 'Approved',
  },
  {
    id: 2,
    employee_id: '1102342',
    employee_name: 'Praveen',
    current_plant: 'MVRLA',
    new_plant: 'LVRLA',
    status: 'Approved',
  },
  {
    id: 3,
    employee_id: '1345083',
    employee_name: 'Javeed Akthar',
    current_plant: 'LVRLA',
    new_plant: 'MVRLA',
    status: 'Approved',
  },
  {
    id: 4,
    employee_id: '1452345',
    employee_name: 'Ramesh',
    current_plant: 'SBD',
    new_plant: 'SBD2',
    status: 'Approved',
  },
  {
    id: 5,
    employee_id: '1502345',
    employee_name: 'Josheph',
    current_plant: 'MVRLA',
    new_plant: 'LVRLA',
    status: 'Approved',
  },
  {
    id: 1,
    employee_id: '1131234',
    employee_name: 'Karthik Kumar',
    current_plant: 'ABD',
    new_plant: 'PLPSCD',
    status: 'Rejected',
  },
  {
    id: 2,
    employee_id: '2131211',
    employee_name: 'Arjun Rathod',
    current_plant: 'MVRLA',
    new_plant: 'ABD',
    status: 'Rejected',
  },
  {
    id: 3,
    employee_id: '1223223',
    employee_name: 'Rahul Kumar',
    current_plant: 'LVRLA',
    new_plant: 'MVRLA',
    status: 'Rejected',
  },
  {
    id: 4,
    employee_id: '2134342',
    employee_name: 'Ishawar Kumar',
    current_plant: 'SBD',
    new_plant: 'SBD2',
    status: 'Rejected',
  },
  {
    id: 5,
    employee_id: '1221342',
    employee_name: 'Arun Kumar TL',
    current_plant: 'MVRLA',
    new_plant: 'LVRLA',
    status: 'Rejected',
  },
];

export const archive = [
  {
    archieve_id: 2,
    archieve_year: '2015-2016',
    company: 'amara raja batteries ltd',
    department: 'production',
    category: 'bb',
    project_title: 'more acid filling cycle time for din50lmf',
    baseline: '19sec/battery',
    target: '12sec/battery',
    result: 'filling cycle time of din 50 lmf reduced from 19 sec to 12 sec/batt.',
    doc_path: 'D:\\Projects\\CIPortal\\Archieve\\2015-2016\\BB\\',
    doc_filename: 'bb(bprk)-opt.ppt',
    doc_filesize: 7193088,
  },
  {
    archieve_id: 3,
    archieve_year: '2015-2016',
    company: 'amara raja batteries ltd',
    department: 'production',
    category: 'bb',
    project_title: 'more boost charge of 12 hours prior for 38b20rmf batteries',
    baseline: '12hour',
    target: '0hour',
    result: 'boost charge reduced from 12 hrs to zero hrs.',
    doc_path: 'D:\\Projects\\CIPortal\\Archieve\\2015-2016\\BB\\',
    doc_filename: '38b20r optimization project - final 14.04.2016-tjn.ppt',
    doc_filesize: 5641216,
  },
  {
    archieve_id: 4,
    archieve_year: '2015-2016',
    company: 'amara raja batteries ltd',
    department: 'production',
    category: 'bb',
    project_title: 'more grid jamming in line 02 hopper',
    baseline: '16.39%',
    target: '4%',
    result: 'grid jam in hopper reduced from 16.39% to 4%',
    doc_path: 'D:\\Projects\\CIPortal\\Archieve\\2015-2016\\BB\\',
    doc_filename: 'grid jam - problem solving.ppt',
    doc_filesize: 10694656,
  },
  {
    archieve_id: 5,
    archieve_year: '2015-2016',
    company: 'amara raja batteries ltd',
    department: 'production',
    category: 'bb',
    project_title: 'reduction of cooling time near heat sealing process in 4d model',
    baseline: '48sec',
    target: '15sec',
    result: 'cycle time reduced from 48 sec to 15 sec.',
    doc_path: 'D:\\Projects\\CIPortal\\Archieve\\2015-2016\\BB\\',
    doc_filename: 'kpn optimization project-heat sealing.ppt',
    doc_filesize: 6833664,
  },
  {
    archieve_id: 6,
    archieve_year: '2015-2016',
    company: 'amara raja batteries ltd',
    department: 'production',
    category: 'bb',
    project_title: 'more formation cycle time for hcv100 (oem) during formation process',
    baseline: '28hrs',
    target: '21hrs',
    result: '7hrs of time reduced/circuit.',
    doc_path: 'D:\\Projects\\CIPortal\\Archieve\\2015-2016\\BB\\',
    doc_filename: '100 ah - oem - boost charge - control phase.ppt',
    doc_filesize: 3786240,
  },
  {
    archieve_id: 7,
    archieve_year: '2015-2016',
    company: 'amara raja batteries ltd',
    department: 'production',
    category: 'bb',
    project_title: 'high rejections in h.v.test',
    baseline: '1.61%',
    target: '0.32%',
    result: 'heat seal leaks reduced from 1.61% to 0.32%.',
    doc_path: 'D:\\Projects\\CIPortal\\Archieve\\2015-2016\\BB\\',
    doc_filename: 'problem solving project-hvt - control phase.ppt',
    doc_filesize: 7207424,
  },
  {
    archieve_id: 8,
    archieve_year: '2015-2016',
    company: 'amara raja batteries ltd',
    department: 'production',
    category: 'bb',
    project_title: 'low productivity in cylinder caster',
    baseline: '1900kg/hr',
    target: '2100kg/hr',
    result: 'productivity increased to 2100kg/hr.',
    doc_path: 'D:\\Projects\\CIPortal\\Archieve\\2015-2016\\BB\\',
    doc_filename: 'optimization project-caster.ppt',
    doc_filesize: 5641216,
  },
  {
    archieve_id: 9,
    archieve_year: '2015-2016',
    company: 'amara raja batteries ltd',
    department: 'production',
    category: 'bb',
    project_title:
      'more plate damages in line-02 catcher due to fork movement stoppages, lh bottom servo stuck up and rh bottom servo stuck up',
    baseline: 'break downs 72.57 hrs / annum',
    target: 'break downs 22.0 hrs/ annum',
    result: 'breakdowns reduced from 6hrs/month to 1.35hrs/month.',
    doc_path: 'D:\\Projects\\CIPortal\\Archieve\\2015-2016\\BB\\',
    doc_filename: 'problem solving project catcher.ppt',
    doc_filesize: 10398720,
  },
  {
    archieve_id: 10,
    archieve_year: '2015-2016',
    company: 'amara raja batteries ltd',
    department: 'quality',
    category: 'bb',
    project_title: 'reduction of post bends among assembled batteries in d26 models.',
    baseline: '11.9%',
    target: '0%',
    result: 'rejections reduced from 11.9% to 0%.',
    doc_path: 'D:\\Projects\\CIPortal\\Archieve\\2015-2016\\BB\\',
    doc_filename: 'bb pbhs ppt - 27.04.2016.ppt',
    doc_filesize: 8449024,
  },
  {
    archieve_id: 11,
    archieve_year: '2015-2016',
    company: 'amara raja batteries ltd',
    department: 'quality',
    category: 'bb',
    project_title: 'low productivity ip215 jars in b900t machine',
    baseline: "576 no's",
    target: "614 no's",
    result: '1hr 18mints of machine time saved with productivity improvement.',
    doc_path: 'D:\\Projects\\CIPortal\\Archieve\\2015-2016\\BB\\',
    doc_filename: 'optimization project 14.12.2015..ppt',
    doc_filesize: 3922432,
  },
];

export const templates = [
  {
    template_id: 1,
    author: 'vinay. s.',
    title: 'six sigma a3 sheet',
    path: 'D:\\Projects2015\\CIPortal\\Document\\Templates\\',
    fname: 'Six Sigma A3 sheet.doc',
    date: '2019-11-19 00:00:00.000',
  },
  {
    template_id: 2,
    author: 'vinay. s.',
    title: 'six sigma project charter for manufacturing',
    path: 'D:\\Projects2015\\CIPortal\\Document\\Templates\\',
    fname: 'Six Sigma Project Charter for Manufacturing.doc',
    date: '2019-11-19 00:00:00.000',
  },
  {
    template_id: 3,
    author: 'vinay. s.',
    title: 'six sigma charter for non manufacturing',
    path: 'D:\\Projects2015\\CIPortal\\Document\\Templates\\',
    fname: 'Six Sigma Charter for Non Manufacturing.doc',
    date: '2019-11-19 00:00:00.000',
  },
  {
    template_id: 4,
    author: 'vinay. s.',
    title: 'six sigma project closure report',
    path: 'D:\\Projects2015\\CIPortal\\Document\\Templates\\',
    fname: 'Six Sigma Project Closure Report.doc',
    date: '2019-11-19 00:00:00.000',
  },
  {
    template_id: 7,
    author: 'battepati sasidhar',
    title: 'six sigma problem solving project template',
    path: 'D:\\Projects2015\\CIPortal\\Document\\Templates\\',
    fname: 'Six Sigma Problem Solving Project Template.ppt',
    date: '2022-04-27 00:00:00.000',
  },
  {
    template_id: 8,
    author: 'battepati sasidhar',
    title: 'six sigma process optimization project template',
    path: 'D:\\Projects2015\\CIPortal\\Document\\Templates\\',
    fname: 'Six Sigma Process Optimization Project Template.ppt',
    date: '2022-04-27 00:00:00.000',
  },
];

export const trainingData = [
  {
    employee_id: '1002345',
    employee_name: 'Arun Kumar',
    department: 'ABD-Assembly',
    grade: 'AU9',
    work_location: 'Andhra Pradesh',
    bussiness_unit: 'Lead Acid',
    division: 'ABD',
    company: 'ARBL',
    batch: '2023',
    year: '2023-2024',
    trainer: 'Ram Kishore',
  },
  {
    employee_id: '1002345',
    employee_name: 'Arun Kumar',
    department: 'ABD-Assembly',
    grade: 'AU9',
    work_location: 'Andhra Pradesh',
    bussiness_unit: 'Lead Acid',
    division: 'ABD',
    company: 'ARBL',
    batch: '2023',
    year: '2023-2024',
    trainer: 'Ram Kishore',
  },
  {
    employee_id: '1002345',
    employee_name: 'Arun Kumar',
    department: 'ABD-Assembly',
    grade: 'AU9',
    work_location: 'Andhra Pradesh',
    bussiness_unit: 'Lead Acid',
    division: 'ABD',
    company: 'ARBL',
    batch: '2023',
    year: '2023-2024',
    trainer: 'Ram Kishore',
  },
  {
    employee_id: '1002345',
    employee_name: 'Arun Kumar',
    department: 'ABD-Assembly',
    grade: 'AU9',
    work_location: 'Andhra Pradesh',
    bussiness_unit: 'Lead Acid',
    division: 'ABD',
    company: 'ARBL',
    batch: '2023',
    year: '2023-2024',
    trainer: 'Ram Kishore',
  },
  {
    employee_id: '1002345',
    employee_name: 'Arun Kumar',
    department: 'ABD-Assembly',
    grade: 'AU9',
    work_location: 'Andhra Pradesh',
    bussiness_unit: 'Lead Acid',
    division: 'ABD',
    company: 'ARBL',
    batch: '2023',
    year: '2023-2024',
    trainer: 'Ram Kishore',
  },
  {
    employee_id: '1002345',
    employee_name: 'Arun Kumar',
    department: 'ABD-Assembly',
    grade: 'AU9',
    work_location: 'Andhra Pradesh',
    bussiness_unit: 'Lead Acid',
    division: 'ABD',
    company: 'ARBL',
    batch: '2023',
    year: '2023-2024',
    trainer: 'Ram Kishore',
  },
  {
    employee_id: '1002345',
    employee_name: 'Arun Kumar',
    department: 'ABD-Assembly',
    grade: 'AU9',
    work_location: 'Andhra Pradesh',
    bussiness_unit: 'Lead Acid',
    division: 'ABD',
    company: 'ARBL',
    batch: '2023',
    year: '2023-2024',
    trainer: 'Ram Kishore',
  },
  {
    employee_id: '1002345',
    employee_name: 'Arun Kumar',
    department: 'ABD-Assembly',
    grade: 'AU9',
    work_location: 'Andhra Pradesh',
    bussiness_unit: 'Lead Acid',
    division: 'ABD',
    company: 'ARBL',
    batch: '2023',
    year: '2023-2024',
    trainer: 'Ram Kishore',
  },
  {
    employee_id: '1002345',
    employee_name: 'Arun Kumar',
    department: 'ABD-Assembly',
    grade: 'AU9',
    work_location: 'Andhra Pradesh',
    bussiness_unit: 'Lead Acid',
    division: 'ABD',
    company: 'ARBL',
    batch: '2023',
    year: '2023-2024',
    trainer: 'Ram Kishore',
  },
  {
    employee_id: '1002345',
    employee_name: 'Arun Kumar',
    department: 'ABD-Assembly',
    grade: 'AU9',
    work_location: 'Andhra Pradesh',
    bussiness_unit: 'Lead Acid',
    division: 'ABD',
    company: 'ARBL',
    batch: '2023',
    year: '2023-2024',
    trainer: 'Ram Kishore',
  },
];
