export const opportunities = [
  {
    id: 1,
    oppurtunity_id: 'ABD/GB/2024-2025/91',
    company: 'ARBL',
    department: 'ABD-Assembly',
    plant: 'ABD',
    pl_id: 122394,
    category: 'Green Belt',
    project_type: 'Type-1',
    savings_type: "Medium",
    estimated_savings: '>1 and <=5 Lakh',
    pl_name : "Arun",
    bussiness_unit : "Lead Acid",
    problem_impact: 'Medium Impact',
    status: 'Open for Assigning',
    impact_socre: 27,
    problem_statement : "Reduction of cycle time in the GROWIN COS process"
  },
  {
    id: 2,
    oppurtunity_id: 'MVRLA/BB/2024-2025/91',
    company: 'ARBL',
    department: 'MVRLA- Grid Casting',
    plant: 'MVRLA',
    pl_id: 1022323,
    pl_name : "Arun",
    category: 'Black Belt',
    project_type: 'Type-2',
    savings_type: 'Low',
    estimated_savings: '>1 and <=5 Lakh',
    bussiness_unit : "Lead Acid",
    problem_impact: 'High Impact',
    status: 'Open for Assigning',
    impact_socre: 92,
    problem_statement : "Reduction of MF5 (TVS) LOCV rejections"
  },
  {
    id: 3,
    oppurtunity_id: 'LVRLA/BB/2024-2025/91',
    company: 'ARBL',
    department: 'LVRLA - Oxide Plant',
    plant: 'LVRLA',
    pl_id: 120394,
    category: 'Black Belt',
    project_type: 'Type-3',
    savings_type: 'High',
    pl_name : "Arun",
    bussiness_unit : "Lead Acid",
    estimated_savings: '<= 1 Lakh',
    problem_impact: 'Low Impact',
    status: 'Project Assign Pending (CIHead)',
    impact_socre: 12,
    problem_statement : "Reduction of MF5 (TVS) LOCV rejections"
  },
  {
    id: 4,
    oppurtunity_id: 'SBD2/GB/2024-2025/91',
    company: 'ARBL',
    department: 'SBD - Grid Casting',
    plant: 'SBD',
    pl_id: 1000221,
    category: 'Green Belt',
    pl_name : "Arun",
    bussiness_unit : "Lead Acid",
    project_type: 'Type-4',
    savings_type: 'Low',
    estimated_savings: '>1 and <=5 Lakh',
    problem_impact: 'Low Impact',
    status: 'Open for Assigning',
    impact_socre: 25,
    problem_statement : "Reduce Briquette's consumption in Powder coating process"
  },
  {
    id: 5,
    oppurtunity_id: 'SBD2/GB/2024-2025/91',
    company: 'ARBL',
    department: 'MVRLA - Grid Casting',
    plant: 'MVRLA',
    pl_id: 10002394,
    bussiness_unit : "Lead Acid",
    category: 'Green Belt',
    project_type : 'Type-5',
    pl_name : "Arun",
    savings_type: 'Low',
    estimated_savings: '>1 and <=5 Lakh',
    problem_impact: 'Low Impact',
    impact_socre: 32,
    status: 'Open for Assigning',
    problem_statement : "Reduction of cycle time in the GROWIN COS process"
  },
  {
    id: 1,
    oppurtunity_id: 'ABD/GB/2024-2025/91',
    company: 'ARBL',
    department: 'ABD-Assembly',
    plant: 'ABD',
    pl_id: 122394,
    category: 'Green Belt',
    project_type: 'Type-1',
    savings_type: "Medium",
    estimated_savings: '>1 and <=5 Lakh',
    pl_name : "Arun",
    bussiness_unit : "Lead Acid",
    problem_impact: 'Medium Impact',
    status: 'Open for Assigning',
    impact_socre: 27,
    problem_statement : "Reduction of cycle time in the GROWIN COS process"
  },
  {
    id: 2,
    oppurtunity_id: 'MVRLA/BB/2024-2025/91',
    company: 'ARBL',
    department: 'MVRLA- Grid Casting',
    plant: 'MVRLA',
    pl_id: 1022323,
    pl_name : "Arun",
    category: 'Black Belt',
    project_type: 'Type-2',
    savings_type: 'Low',
    estimated_savings: '>1 and <=5 Lakh',
    bussiness_unit : "Lead Acid",
    problem_impact: 'High Impact',
    status: 'Open for Assigning',
    impact_socre: 92,
    problem_statement : "Reduction of MF5 (TVS) LOCV rejections"
  },
  {
    id: 3,
    oppurtunity_id: 'LVRLA/BB/2024-2025/91',
    company: 'ARBL',
    department: 'LVRLA - Oxide Plant',
    plant: 'LVRLA',
    pl_id: 120394,
    category: 'Black Belt',
    project_type: 'Type-3',
    savings_type: 'High',
    pl_name : "Arun",
    bussiness_unit : "Lead Acid",
    estimated_savings: '<= 1 Lakh',
    problem_impact: 'Low Impact',
    status: 'Project Assign Pending (CIHead)',
    impact_socre: 12,
    problem_statement : "Reduction of MF5 (TVS) LOCV rejections"
  },
  {
    id: 4,
    oppurtunity_id: 'SBD2/GB/2024-2025/91',
    company: 'ARBL',
    department: 'SBD - Grid Casting',
    plant: 'SBD',
    pl_id: 1000221,
    category: 'Green Belt',
    pl_name : "Arun",
    bussiness_unit : "Lead Acid",
    project_type: 'Type-4',
    savings_type: 'Low',
    estimated_savings: '>1 and <=5 Lakh',
    problem_impact: 'Low Impact',
    status: 'Open for Assigning',
    impact_socre: 25,
    problem_statement : "Reduce Briquette's consumption in Powder coating process"
  },
  {
    id: 5,
    oppurtunity_id: 'SBD2/GB/2024-2025/91',
    company: 'ARBL',
    department: 'MVRLA - Grid Casting',
    plant: 'MVRLA',
    pl_id: 10002394,
    bussiness_unit : "Lead Acid",
    category: 'Green Belt',
    project_type : 'Type-5',
    pl_name : "Arun",
    savings_type: 'Low',
    estimated_savings: '>1 and <=5 Lakh',
    problem_impact: 'Low Impact',
    impact_socre: 32,
    status: 'Open for Assigning',
    problem_statement : "Reduction of cycle time in the GROWIN COS process"
  },{
    id: 1,
    oppurtunity_id: 'ABD/GB/2024-2025/91',
    company: 'ARBL',
    department: 'ABD-Assembly',
    plant: 'ABD',
    pl_id: 122394,
    category: 'Green Belt',
    project_type: 'Type-1',
    savings_type: "Medium",
    estimated_savings: '>1 and <=5 Lakh',
    pl_name : "Arun",
    bussiness_unit : "Lead Acid",
    problem_impact: 'Medium Impact',
    status: 'Open for Assigning',
    impact_socre: 27,
    problem_statement : "Reduction of cycle time in the GROWIN COS process"
  },
  {
    id: 2,
    oppurtunity_id: 'MVRLA/BB/2024-2025/91',
    company: 'ARBL',
    department: 'MVRLA- Grid Casting',
    plant: 'MVRLA',
    pl_id: 1022323,
    pl_name : "Arun",
    category: 'Black Belt',
    project_type: 'Type-2',
    savings_type: 'Low',
    estimated_savings: '>1 and <=5 Lakh',
    bussiness_unit : "Lead Acid",
    problem_impact: 'High Impact',
    status: 'Open for Assigning',
    impact_socre: 92,
    problem_statement : "Reduction of MF5 (TVS) LOCV rejections"
  },
  {
    id: 3,
    oppurtunity_id: 'LVRLA/BB/2024-2025/91',
    company: 'ARBL',
    department: 'LVRLA - Oxide Plant',
    plant: 'LVRLA',
    pl_id: 120394,
    category: 'Black Belt',
    project_type: 'Type-3',
    savings_type: 'High',
    pl_name : "Arun",
    bussiness_unit : "Lead Acid",
    estimated_savings: '<= 1 Lakh',
    problem_impact: 'Low Impact',
    status: 'Project Assign Pending (CIHead)',
    impact_socre: 12,
    problem_statement : "Reduction of MF5 (TVS) LOCV rejections"
  },
  {
    id: 4,
    oppurtunity_id: 'SBD2/GB/2024-2025/91',
    company: 'ARBL',
    department: 'SBD - Grid Casting',
    plant: 'SBD',
    pl_id: 1000221,
    category: 'Green Belt',
    pl_name : "Arun",
    bussiness_unit : "Lead Acid",
    project_type: 'Type-4',
    savings_type: 'Low',
    estimated_savings: '>1 and <=5 Lakh',
    problem_impact: 'Low Impact',
    status: 'Open for Assigning',
    impact_socre: 25,
    problem_statement : "Reduce Briquette's consumption in Powder coating process"
  },
  {
    id: 5,
    oppurtunity_id: 'SBD2/GB/2024-2025/91',
    company: 'ARBL',
    department: 'MVRLA - Grid Casting',
    plant: 'MVRLA',
    pl_id: 10002394,
    bussiness_unit : "Lead Acid",
    category: 'Green Belt',
    project_type : 'Type-5',
    pl_name : "Arun",
    savings_type: 'Low',
    estimated_savings: '>1 and <=5 Lakh',
    problem_impact: 'Low Impact',
    impact_socre: 32,
    status: 'Open for Assigning',
    problem_statement : "Reduction of cycle time in the GROWIN COS process"
  },
];