name: Build & Deploy to SERVER

on:
  push:
    branches:
      - master  # Adjust as needed

jobs:
  build-and-push:
    name: Build and Push Docker Image to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.ACCESS_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/itsapk/ci-portal-ui:latest .

     

      - name: Push Docker image to GHCR
        run: docker push ghcr.io/itsapk/ci-portal-ui:latest

  deploy:
    name: Deploy to SERVER
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: SSH into SERVER and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}  
          script: |
            docker login ghcr.io -u ${{ github.actor }} --password ${{ secrets.ACCESS_TOKEN }}
            docker pull ghcr.io/${{ github.actor }}/ci-portal-ui:latest
            docker stop my_app || true
            docker rm my_app || true
            docker run -d --name my_app -p 3241:3241 --restart unless-stopped ghcr.io/${{ github.actor }}/ci-portal-ui:latest
